# Generated by Django 3.1.6 on 2021-06-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_a101_bolges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
