# Generated by Django 3.1.6 on 2021-06-12 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ms_a101_bolges', '0004_remove_depotorders_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotorders',
            name='user_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
