# Generated by Django 3.1.6 on 2021-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_a101_bolges', '0006_auto_20210612_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('Adet', 'Adet'), ('Kilo', 'Kilo')], max_length=10)),
                ('price', models.FloatField(default=0)),
                ('destination_bolge', models.CharField(choices=[('serik', 'serik'), ('lüleburgaz', 'lüleburgaz'), ('sakarya', 'sakarya')], max_length=30)),
                ('termin', models.DateTimeField()),
                ('slot', models.CharField(choices=[('07-12', '07-12'), ('12-19', '12-19')], max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
