# Generated by Django 3.1.6 on 2021-07-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_a101_bolges', '0007_localsupplierorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depotorder',
            old_name='quantity',
            new_name='palet',
        ),
    ]
