# Generated by Django 3.1.6 on 2021-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_a101_bolges', '0009_auto_20210701_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotorder',
            name='fruit_vegetable_name',
            field=models.CharField(max_length=20),
        ),
    ]
