# Generated by Django 3.1.6 on 2021-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_a101_bolges', '0012_auto_20210703_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsupplierorder',
            name='slot',
            field=models.CharField(choices=[('07:00-12:00', '07:00-12:00'), ('12:00-19:00', '12:00-19:00')], max_length=20),
        ),
    ]
