# Generated by Django 3.1.6 on 2021-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_a101_bolges', '0014_auto_20210801_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsupplierorder',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
