# Generated by Django 3.1.6 on 2021-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_a101_bolges', '0015_auto_20210801_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotorder',
            name='fruit_vegetable_name_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
