# Generated by Django 3.1.6 on 2021-07-02 21:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import msdepot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeyveSebze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meyve_sebze_adi', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('Adet', 'Adet'), ('Kilo', 'Kilo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MeyveSebzeYeni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_vegetable_name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('Adet', 'Adet'), ('Kilo', 'Kilo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RakipFiyatTakip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_vegetable_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('rakip', models.CharField(max_length=10)),
                ('indirim', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TedarikciAnket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2015), msdepot.models.max_value_current_year])),
                ('month', models.CharField(choices=[('Ocak', 'Ocak'), ('Şubat', 'Şubat'), ('Mart', 'Mart'), ('Nisan', 'Nisan'), ('Mayıs', 'Mayıs'), ('Haziran', 'Haziran'), ('Temmuz', 'Temmuz'), ('Ağustos', 'Ağustos'), ('Eylül', 'Eylül'), ('Ekim', 'Ekim'), ('Kasım', 'Kasım'), ('Aralık', 'Aralık')], max_length=15)),
                ('supplier', models.CharField(max_length=50)),
                ('bulunurluk', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5)),
                ('tazelik', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5)),
                ('temizlik', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5)),
                ('duzen', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5)),
                ('personel_kisisel_bakimi', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5)),
                ('anket_date', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IhaleYeni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('kasa_ebati', models.CharField(choices=[('30x40x15', '30x40x15'), ('20x30x20', '20x30x20')], max_length=30)),
                ('paletteki_kasa_sayisi', models.IntegerField()),
                ('palet_olcusu', models.CharField(choices=[('euro', 'euro'), ('dusseldorf', 'dusseldorf')], max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('teslim_tarihi', models.DateTimeField()),
                ('ihale_date', models.DateTimeField(auto_now_add=True)),
                ('ihale_end_date', models.DateField()),
                ('spekt_aciklama', models.CharField(max_length=300)),
                ('sevk_kosullari', models.CharField(max_length=50)),
                ('koli_kosullari', models.CharField(max_length=50)),
                ('fruit_vegetable_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.meyvesebzeyeni')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IhaleTeklif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ihale_teklif_date', models.DateTimeField(auto_now_add=True)),
                ('fiyat', models.FloatField()),
                ('ihale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.ihaleyeni')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ihale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_vegetable_name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('ihale_date', models.DateTimeField(auto_now_add=True)),
                ('ihale_end_date', models.DateField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
