# Generated by Django 3.1.6 on 2021-07-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihaleyeni',
            name='hedef_fiyat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
