# Generated by Django 3.1.6 on 2021-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0002_ihaleyeni_hedef_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihaleteklif',
            name='ihale_id',
            field=models.CharField(max_length=30),
        ),
    ]
