# Generated by Django 3.1.6 on 2021-07-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0003_auto_20210703_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihaleteklif',
            name='ihale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.ihaleyeni'),
        ),
    ]
