# Generated by Django 3.1.6 on 2021-07-03 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msdepot', '0004_auto_20210703_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='IhaleIkınciTur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedef_fiyat', models.FloatField(blank=True, default=None, null=True)),
                ('ihale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.ihaleyeni')),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
