# Generated by Django 3.1.6 on 2021-07-03 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msdepot', '0005_ihaleikıncitur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IhaleIkınciTur',
            new_name='IhaleIkinciTur',
        ),
    ]
