# Generated by Django 3.1.6 on 2021-07-03 15:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0006_auto_20210703_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihaleikincitur',
            name='suppliers',
            field=jsonfield.fields.JSONField(),
        ),
    ]
