# Generated by Django 3.1.6 on 2021-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0007_auto_20210703_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihaleikincitur',
            name='suppliers',
            field=models.CharField(max_length=100),
        ),
    ]
