# Generated by Django 3.1.6 on 2021-07-03 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msdepot', '0008_auto_20210703_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihaleikincitur',
            name='suppliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
