# Generated by Django 3.1.6 on 2021-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0009_auto_20210703_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihaleikincitur',
            name='suppliers',
            field=models.CharField(max_length=10),
        ),
    ]
