# Generated by Django 3.1.6 on 2021-07-03 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msdepot', '0011_auto_20210703_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihaleikincitur',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='ihaleikincitur',
            name='suppliers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
