# Generated by Django 3.1.6 on 2021-07-03 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0012_auto_20210703_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihaleikincitur',
            name='ihale_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
