# Generated by Django 3.1.6 on 2021-07-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0014_ihaleikinciturteklif'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaglantiliUrunIhalesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_icerikleri_standartlari', models.CharField(blank=True, default=None, max_length=220, null=True)),
                ('koli_icerigi', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('palet_icerigi', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ambalaj_maddesi', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sabit_fiyat_garantisi', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('raf_omru', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tat_testi_sonucu', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tavsiye', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('karar', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('yorum', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('month', models.CharField(blank=True, choices=[('Ocak', 'Ocak'), ('Şubat', 'Şubat'), ('Mart', 'Mart'), ('Nisan', 'Nisan'), ('Mayıs', 'Mayıs'), ('Haziran', 'Haziran'), ('Temmuz', 'Temmuz'), ('Ağustos', 'Ağustos'), ('Eylül', 'Eylül'), ('Ekim', 'Ekim'), ('Kasım', 'Kasım'), ('Aralık', 'Aralık')], default=None, max_length=15, null=True)),
                ('planlanan_hedef_tonaj', models.FloatField(blank=True, default=None, null=True)),
                ('fruit_vegetable_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.meyvesebzeyeni')),
            ],
        ),
    ]
