# Generated by Django 3.1.6 on 2021-07-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0016_baglantiliurunihalesi_ihale_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaglantiliIhaleAyHedefTonaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('planlanan_hedef_tonaj', models.FloatField(blank=True, default=None, null=True)),
                ('baglantiliihaleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.baglantiliurunihalesi')),
            ],
        ),
    ]
