# Generated by Django 3.1.6 on 2021-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0017_baglantiliihaleayhedeftonaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baglantiliihaleayhedeftonaj',
            name='baglantiliihaleid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
