# Generated by Django 3.1.6 on 2021-07-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0018_auto_20210712_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baglantiliihaleayhedeftonaj',
            name='baglantiliihaleid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='msdepot.baglantiliurunihalesi'),
            preserve_default=False,
        ),
    ]
