# Generated by Django 3.1.6 on 2021-07-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0020_baglantiliihaleteklif'),
    ]

    operations = [
        migrations.AddField(
            model_name='baglantiliihaleayhedeftonaj',
            name='planlanan_hedef_fiyat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='baglantiliihaleteklif',
            name='planlanan_hedef_fiyat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='baglantiliurunihalesi',
            name='planlanan_hedef_fiyat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
