# Generated by Django 3.1.6 on 2021-08-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0021_auto_20210713_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meyvesebzeyeni',
            old_name='fruit_vegetable_name',
            new_name='fruit_vegetable_name_yeni',
        ),
        migrations.AddField(
            model_name='ihaleyeni',
            name='fruit_vegetable_kod',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meyvesebzeyeni',
            name='fruit_vegetable_kod_yeni',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
