# Generated by Django 3.1.6 on 2021-08-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0024_auto_20210802_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihaleyeni',
            name='fruit_vegetable_kod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.meyvesebzeyeni'),
        ),
    ]
