# Generated by Django 3.1.6 on 2021-08-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0027_auto_20210802_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihaleyeni',
            name='teslim_yeri',
            field=models.CharField(blank=True, choices=[('a101_bolge_depoları', 'A101 Bölge Depoları'), ('a101_antalya_meyve_sebze_deposu', 'A101 Antalya Meyve Sebze Deposu')], default=None, max_length=50, null=True),
        ),
    ]
