# Generated by Django 3.1.6 on 2021-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0028_ihaleyeni_teslim_yeri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihaleyeni',
            name='teslim_yeri',
            field=models.CharField(blank=True, choices=[('A101 Bölge Depoları', 'A101 Bölge Depoları'), ('A101 Antalya Meyve Sebze Deposu', 'A101 Antalya Meyve Sebze Deposu')], default=None, max_length=50, null=True),
        ),
    ]
