# Generated by Django 3.1.6 on 2021-06-14 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mssupplier', '0002_auto_20210614_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstock',
            name='explanation',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
