# Generated by Django 3.1.6 on 2021-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssupplier', '0003_supplierstock_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstock',
            name='explanation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
