# Generated by Django 3.1.6 on 2021-07-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssupplier', '0004_auto_20210614_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstock',
            name='current_stock',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierstock',
            name='current_unit',
            field=models.CharField(blank=True, choices=[('Adet', 'Adet'), ('Kilo', 'Kilo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='supplierstock',
            name='yearly_sales_capacity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierstock',
            name='yearly_unit',
            field=models.CharField(blank=True, choices=[('Adet', 'Adet'), ('Kilo', 'Kilo')], max_length=10),
        ),
    ]
