# Generated by Django 3.1.6 on 2021-07-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0014_ihaleikinciturteklif'),
        ('mssupplier', '0006_auto_20210704_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstock',
            name='fruit_vegetable_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.meyvesebzeyeni'),
        ),
    ]
