# Generated by Django 3.1.6 on 2021-08-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0025_auto_20210802_0101'),
        ('mssupplier', '0007_auto_20210704_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstock',
            name='fruit_vegetable_name',
            field=models.ForeignKey(db_column='fruit_vegetable_name_yeni', on_delete=django.db.models.deletion.CASCADE, to='msdepot.meyvesebzeyeni'),
        ),
    ]
