# Generated by Django 3.1.6 on 2021-08-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdepot', '0027_auto_20210802_2134'),
        ('mssupplier', '0008_auto_20210802_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstock',
            name='fruit_vegetable_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdepot.meyvesebzeyeni'),
        ),
    ]
