# Generated by Django 3.1.6 on 2021-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210614_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(choices=[('MsDepo', 'MsDepo'), ('Bölge', 'Bölge')], max_length=10),
        ),
    ]
