# Generated by Django 3.1.6 on 2021-06-21 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='termin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
