# Generated by Django 3.1.6 on 2021-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_termin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='termin',
            field=models.DateTimeField(),
        ),
    ]
