# Generated by Django 3.1.6 on 2021-06-21 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210621_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='termin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
