# Generated by Django 3.1.6 on 2021-07-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210621_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slot',
            field=models.CharField(choices=[('07:00-12:00', '07:00-12:00'), ('12:00-19:00', '12:00-19:00')], max_length=20),
        ),
    ]
