# Generated by Django 3.1.6 on 2021-07-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20210705_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
