# Generated by Django 3.1.6 on 2021-07-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20210705_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
